
updateDocsWhiteList:
  - BUG
  - Chore

updateDocsComment: >
  Thanks for opening this pull request! The maintainers of this repository would appreciate it if you would update some of our documentation based on your changes.
requestInfoDefaultTitles:
  - update readme.md
  - updates

requestInfoReplyComment: >
  We would appreciate it if you could provide us with more info about this issue/pr!
requestInfoLabelToAdd: request-more-info

newPRWelcomeComment: >
  :sparkles: Thanks so much for opening your first PR here, make sure to follow the contributing guidelines! :sparkles:
  [Congrats!](https://media.giphy.com/media/o0vwzuFwCGAFO/giphy.gif)
firstPRMergeComment: >
  Congrats on merging your first pull request here! :tada:
firstIssueWelcomeComment: >
  Thanks for opening this issue, please make sure you follow our issue template!
sentimentBotToxicityThreshold: .8

sentimentBotReplyComment: >
  Please be sure to review the code of conduct and be respectful of other users. cc/ @hiimbex
lockThreads:
  toxicityThreshold: .5
  numComments: 3
  setTimeInHours: 1
  replyComment: >
    This thread is being locked due to exceeding the toxicity minimums. cc/ @hiimbex
